In [141]:
from pipeline import Pipeline
from transforms import Resample, LPF, Mean, ICA, Stats, Abs
from data_utils import load_data
import os
import numpy as np
import cPickle
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [54]:
%time feats = pipe.apply(X_1)

Wall time: 2.67 s


In [144]:
%time X_1, y_1, files_1 = load_data('train_1', sample=20)

found 20 files
Wall time: 44 ms


In [114]:
pipe = Pipeline([Stats()])

In [142]:
pipe.to_file(X_1, files_1, 'test', y_1)

In [145]:
pip2 = Pipeline([Resample(600)])

In [146]:
feats = pip2.apply(X_1)

In [148]:
feats.shape

(20L, 16L, 600L)

In [83]:
data = [feats, y_1, files_1]

In [85]:
data[0].shape, data[1].shape, data[2].shape

((20L, 16L, 3L), (20L,), (20L,))

In [109]:
dest_dir = 'feature_vectors'
data_name = 'test'
name = 'mean_'

os.path.join(dest_dir, data_name+'_'+name+'.pkl')

'feature_vectors\\test_mean_.pkl'

In [110]:
import os

In [118]:
import cPickle

In [120]:
with open(os.path.join('feature_vectors', 'train_1_chMean.pkl'), 'rb') as f:
    data = cPickle.load(f)

In [123]:
data[0]

array([[ -9.83683321e-07,   1.89917665e-02,   1.10198848e-01, ...,
          2.94296294e-01,   2.03892991e-01,   4.82356511e-02],
       [ -3.19417325e-07,   1.00683793e-03,   9.13381204e-02, ...,
          2.40331247e-01,   1.64330199e-01,   4.14782763e-02],
       [  3.66210955e-08,   1.00977381e-03,   1.14871174e-01, ...,
          3.28620642e-01,   2.18247324e-01,   7.17839375e-02],
       ..., 
       [ -1.70389811e-07,  -5.99753344e-04,   8.97090044e-03, ...,
          2.91291699e-02,   3.84663343e-02,   1.12210764e-02],
       [  9.05354796e-08,   5.70511853e-04,   3.24630216e-02, ...,
          7.77836889e-02,   7.04036802e-02,   2.09332090e-02],
       [ -1.35803219e-07,   5.55064296e-03,   2.91998088e-02, ...,
          7.55627751e-02,   5.44629954e-02,   5.82056493e-03]], dtype=float32)

In [125]:
data[2]

array(['1_1000_0.mat', '1_1001_0.mat', '1_1002_0.mat', ..., '1_1013_0.mat',
       '1_1014_0.mat', '1_1017_0.mat'], 
      dtype='|S12')

In [126]:
with open(os.path.join('feature_vectors', 'train_1_chMean_abs.pkl'), 'rb') as f:
    data2 = cPickle.load(f)

In [127]:
data2[2]

array(['1_1000_0.mat', '1_1001_0.mat', '1_1002_0.mat', ..., '1_1013_0.mat',
       '1_1014_0.mat', '1_1017_0.mat'], 
      dtype='|S12')

In [128]:
data[0].shape

(1267L, 16L)

In [129]:
data2[0].shape

(1267L, 16L)

In [135]:
np.hstack([data[0], data2[0]])

(1267L, 32L)

In [136]:
data[0][0]

array([ -9.83683321e-07,   1.89917665e-02,   1.10198848e-01,
        -7.03443214e-02,   1.21276408e-01,  -8.58199671e-02,
        -4.71746586e-02,  -2.05775425e-01,  -1.24229565e-01,
        -2.28837758e-01,  -2.46325850e-01,   2.87570536e-01,
         3.69416058e-01,   2.94296294e-01,   2.03892991e-01,
         4.82356511e-02], dtype=float32)

In [137]:
data2[0][0]

array([  9.83683321e-07,   1.89917665e-02,   1.10198848e-01,
         7.03443214e-02,   1.21276408e-01,   8.58199671e-02,
         4.71746586e-02,   2.05775425e-01,   1.24229565e-01,
         2.28837758e-01,   2.46325850e-01,   2.87570536e-01,
         3.69416058e-01,   2.94296294e-01,   2.03892991e-01,
         4.82356511e-02], dtype=float32)