In [2]:
from data_utils import load_data
import matplotlib.pyplot as plt
import seaborn as sns
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [47]:
%time X, y, files = load_data('train_1', shape='flat')

loading 1301 with 7 processes.
Wall time: 4min 31s


In [60]:
from sklearn.preprocessing import normalize
from sklearn.cross_validation import train_test_split


normalize(X, copy=False)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1337)

In [61]:
X_train_2d = X_train.reshape((len(X_train), 16, 600, 1))
X_test_2d = X_test.reshape((len(X_test), 16, 600, 1))


In [124]:
from keras.models import Sequential
from keras.layers import Convolution2D, Dense, Dropout, Flatten, MaxPooling2D, BatchNormalization
from keras.callbacks import EarlyStopping
import numpy as np

In [125]:
cnn = Sequential()
cnn.add(Convolution2D(64, 3, 1, border_mode="same", activation="relu", input_shape=(16, 600, 1)))
cnn.add(MaxPooling2D(pool_size=(2, 1)))
cnn.add(Flatten())
cnn.add(Dense(512, activation="relu"))
cnn.add(Dropout(0.9))
cnn.add(Dense(512, activation="relu"))
cnn.add(Dropout(0.9))
cnn.add(Dense(1, init='normal', activation='sigmoid'))
cnn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [127]:
earlystop = EarlyStopping(patience=20)

In [128]:
cnn.fit(X_train_2d, y_train, nb_epoch=50, validation_data=(X_test_2d, y_test), callbacks=[earlystop])

Train on 871 samples, validate on 430 samples
Epoch 1/50
871/871 [==============================] - 0s - loss: 0.0565 - acc: 0.9805 - val_loss: 0.8788 - val_acc: 0.8721
Epoch 2/50
871/871 [==============================] - 0s - loss: 0.0572 - acc: 0.9770 - val_loss: 0.8686 - val_acc: 0.8721
Epoch 3/50
871/871 [==============================] - 0s - loss: 0.0622 - acc: 0.9770 - val_loss: 0.9631 - val_acc: 0.8744
Epoch 4/50
871/871 [==============================] - 0s - loss: 0.0531 - acc: 0.9816 - val_loss: 1.0101 - val_acc: 0.8721
Epoch 5/50
871/871 [==============================] - 0s - loss: 0.0503 - acc: 0.9828 - val_loss: 1.0567 - val_acc: 0.8744
Epoch 6/50
871/871 [==============================] - 0s - loss: 0.0445 - acc: 0.9862 - val_loss: 0.9820 - val_acc: 0.8698
Epoch 7/50
871/871 [==============================] - 0s - loss: 0.0452 - acc: 0.9816 - val_loss: 1.1964 - val_acc: 0.8791
Epoch 8/50
871/871 [==============================] - 0s - loss: 0.0562 - acc: 0.9793 - val_l

In [129]:
preds = cnn.predict_classes(X_test_2d)

416/430 [============================>.] - ETA: 0s

In [130]:
from sklearn.metrics import confusion_matrix

In [131]:
preds_train = cnn.predict_classes(X_train_2d)

864/871 [============================>.] - ETA: 0s

In [132]:
confusion_matrix(y_train, preds_train)

array([[768,   0],
       [  6,  97]])

In [133]:
confusion_matrix(y_test, preds)

array([[380,   4],
       [ 46,   0]])

In [134]:
from sklearn.metrics import roc_auc_score

In [135]:
roc_auc_score(y_test, preds)

0.49479166666666669

In [136]:
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0,

In [107]:
roc_auc_score(y_train, preds_train)

0.5

In [154]:
X_test_1d = X_test.reshape((len(X_test), 16*600, 1))
X_train_1d = X_train.reshape((len(X_train), 16*600, 1))
X_train_1d.shape

(871L, 9600L, 1L)

In [109]:
from keras.layers import Convolution1D, AveragePooling1D

In [110]:
model = Sequential()

model.add(Convolution1D(nb_filter=6,
                        filter_length=3,
                        border_mode="valid",
                        activation="relu", 
                        input_shape=(9600, 1)))
model.add(AveragePooling1D(pool_length=2))
model.add(Flatten())
model.add(Dense(512, activation="relu"))
model.add(Dropout(0.9))
model.add(Dense(1, init='normal', activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [144]:
model.fit(X_train_1d, y_train, nb_epoch=50, validation_data=(X_test_1d, y_test), callbacks=[earlystop])

Train on 871 samples, validate on 430 samples
Epoch 1/50
871/871 [==============================] - 0s - loss: 0.0402 - acc: 0.9851 - val_loss: 0.6439 - val_acc: 0.8767
Epoch 2/50
871/871 [==============================] - 0s - loss: 0.0458 - acc: 0.9828 - val_loss: 0.6675 - val_acc: 0.8767
Epoch 3/50
871/871 [==============================] - 0s - loss: 0.0380 - acc: 0.9874 - val_loss: 0.7219 - val_acc: 0.8791
Epoch 4/50
871/871 [==============================] - 0s - loss: 0.0356 - acc: 0.9885 - val_loss: 0.7017 - val_acc: 0.8767
Epoch 5/50
871/871 [==============================] - 0s - loss: 0.0360 - acc: 0.9885 - val_loss: 0.7840 - val_acc: 0.8860
Epoch 6/50
871/871 [==============================] - 0s - loss: 0.0363 - acc: 0.9851 - val_loss: 0.6832 - val_acc: 0.8744
Epoch 7/50
871/871 [==============================] - 0s - loss: 0.0360 - acc: 0.9885 - val_loss: 0.7700 - val_acc: 0.8860
Epoch 8/50
871/871 [==============================] - 0s - loss: 0.0306 - acc: 0.9885 - val_l

In [147]:
preds_train_1d = model.predict_classes(X_train_1d)
preds_1d = model.predict_classes(X_test_1d)

352/430 [=======================>......] - ETA: 0s

In [145]:
roc_auc_score(y_train, preds_train_1d)

0.82524271844660202

In [148]:
roc_auc_score(y_test, preds_1d)

0.49479166666666669

In [149]:
from keras.layers import LSTM

In [156]:
model = Sequential()
model.add(LSTM(4, input_shape=(9600, 1)))
model.add(Dense(1))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [157]:
model.fit(X_train_1d, y_train, nb_epoch=50, validation_data=(X_test_1d, y_test), callbacks=[earlystop])

Train on 871 samples, validate on 430 samples
Epoch 1/50
871/871 [==============================] - 303s - loss: 0.4320 - acc: 0.8817 - val_loss: 0.3397 - val_acc: 0.8930
Epoch 2/50
871/871 [==============================] - 310s - loss: 0.3647 - acc: 0.8817 - val_loss: 0.3400 - val_acc: 0.8930
Epoch 3/50
871/871 [==============================] - 311s - loss: 0.3637 - acc: 0.8817 - val_loss: 0.3399 - val_acc: 0.8930
Epoch 4/50
871/871 [==============================] - 308s - loss: 0.3647 - acc: 0.8817 - val_loss: 0.3396 - val_acc: 0.8930
Epoch 5/50
871/871 [==============================] - 303s - loss: 0.3658 - acc: 0.8817 - val_loss: 0.3396 - val_acc: 0.8930
Epoch 6/50
871/871 [==============================] - 308s - loss: 0.3657 - acc: 0.8817 - val_loss: 0.3395 - val_acc: 0.8930
Epoch 7/50
871/871 [==============================] - 309s - loss: 0.3654 - acc: 0.8817 - val_loss: 0.3404 - val_acc: 0.8930
Epoch 8/50
871/871 [==============================] - 307s - loss: 0.3642 - acc